#@TYPE: Machine
#@NAME: NXP i.MX 8M Mini NavQ board with LPDDR4 memory
#@SOC: i.MX8MM
#@DESCRIPTION: Machine configuration for NXP i.MX 8M Mini NavQ board with LPDDR4 memory
#@MAINTAINER: <customer-service@emcraft.com>

require conf/machine/include/imx8mm-evk.inc

KERNEL_DEVICETREE = "freescale/imx8mm-navq.dtb"

WKS_FILE_DEPENDS += "imx-m4-demos"
IMAGE_BOOT_FILES += " \
    imx8mm_m4_TCM_hello_world.bin \
    imx8mm_m4_TCM_rpmsg_lite_pingpong_rtos_linux_remote.bin \
    imx8mm_m4_TCM_rpmsg_lite_str_echo_rtos.bin \
    imx8mm_m4_TCM_sai_low_power_audio.bin \
"

UBOOT_CONFIG_BASENAME = "imx8mm_navq"

# Set DDR FIRMWARE
DDR_FIRMWARE_NAME = " \
    lpddr4_pmu_train_1d_imem.bin \
    lpddr4_pmu_train_1d_dmem.bin \
    lpddr4_pmu_train_2d_imem.bin \
    lpddr4_pmu_train_2d_dmem.bin \
"

# Set u-boot DTB
UBOOT_DTB_NAME = "imx8mm-navq.dtb"

# Set imx-mkimage boot target
IMXBOOT_TARGETS_BASENAME = "flash_evk"

# Add additional firmware
MACHINE_FIRMWARE:append = " linux-firmware-ath10k"
